before_script:
- psql -c 'create database total_being_reset_test;' -U postgres
language: ruby
rvm:
- 2.6.3
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
services: postgresql
deploy:
  provider: heroku
  api_key:
    secure: 3Ou7Ku2VL/RXiGemkWi8hp8jZkab7AQWOdgHhgV46/ANVuYgzcR/uceMESmsuhCG57Dhp6Ff5Es0DMZd3plxMrrlLWpZmgVPfVKv3gNwnatfCoZZU1STXc7U0s2rB2ojTCYt+HbDswnDfg5T5w78fpqUiiqcFOK9ediKufnOR24S35ANddH7RbhU/6I5RqKiqQOHvnejtj+UDM9wUHPEqymJEyGy77qZmUi1Uuaptn88E01PPB6/8ZnCyIb18AsxAggLkVI4XjO8Q6C/JS8dLXms3vboBVxasNWjPKIzEnA0rKDfH2XiLhZvjT9bne5BwIswMuAD9etd25j7Kv7IXyftVFqWBq3f941m28fgpLf/JFB4QwKM3FTRuWZOrzngtJlpCz4+QQM5KpSVPqvOKaCUy9j1WOG+Sn9Z3KD/G9DET0Ev+YIy4XEQlqhJoQptKlmbE52lYm3CcWG7yP/DAN7MDevTj6jtSg83NGkFxpwPEEFsvLuAT20MPMnUmOllrkVrsVlqvxxfxP1ENkg9LHqM2f081jb/BQEa7zMo3rSrhWpjdhmw/8K67y8DlnktMqkWsOcvoS/XvUrGw7w5lWM3y9VWG0uLlVwH7elGuxYT7OZDg+CfE3lvhyV+ejX3HX9Kccy37Pi8t6uUmRb4oDyUOeu8fgc/xdKG0jlzuJA=
  app: total-being-reset
  on:
    repo: johnktravers/total_being_reset
